#!/usr/bin/env python3
"""
Generate Adafruit GFX font header from font1.png

Non-ASCII character mapping:
  0x7F -> £ (pound sterling)  use FONT1_POUND constant
  0x80 -> € (euro)            use FONT1_EURO  constant
"""

from PIL import Image

# Characters in left-to-right order as they appear in font1.png
CHARS = (
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    'abcdefghijklmnopqrstuvwxyz'
    '0123456789'
    ":;.,-()&/\\!?'\"+*=^%$@[]{}£<>#|_`€~"
)

CELL_W      = 30
CELL_H      = 54
BASELINE    = 41    # 0-based row index of baseline within cell
CHAR_GAP    = 4     # pixels between characters (added after visible width)
SPACE_ADV   = 30    # xAdvance for ' '
THRESHOLD   = 128   # brightness threshold: >= foreground, < background
FONT_NAME   = 'Font1'
OUT_PATH    = 'depart/font1.h'


def char_code(c):
    if c == '£': return 0x7F
    if c == '€': return 0x80
    return ord(c)


def main():
    img = Image.open('font1.png').convert('RGB')
    iw, ih = img.size
    px = img.load()

    expected_w = len(CHARS) * CELL_W
    if iw != expected_w or ih != CELL_H:
        raise ValueError(f"Image {iw}x{ih}, expected {expected_w}x{CELL_H}")
    print(f"Processing {len(CHARS)} chars from {iw}x{ih} image")

    bitmap_bytes = []
    glyphs = {}  # code -> (bitmapOffset, w, h, xAdvance, xOffset, yOffset)

    for i, c in enumerate(CHARS):
        cx = i * CELL_W
        code = char_code(c)

        # Find tight bounding box of lit pixels within the cell
        min_row = min_col = 9999
        max_row = max_col = -1
        for row in range(CELL_H):
            for col in range(CELL_W):
                r, g, b = px[cx + col, row]
                if max(r, g, b) >= THRESHOLD:
                    if row < min_row: min_row = row
                    if row > max_row: max_row = row
                    if col < min_col: min_col = col
                    if col > max_col: max_col = col

        if max_row == -1:
            glyphs[code] = (0, 0, 0, CHAR_GAP, 0, 0)
            print(f"  0x{code:02X} '{c}': (empty)")
            continue

        gw = max_col - min_col + 1
        gh = max_row - min_row + 1
        # Add 2 dark columns on the right (inter-LED gap) unless the visible
        # width is already divisible by 4.
        pad = 0 if gw % 4 == 0 else 2
        gw += pad
        x_advance = gw + CHAR_GAP
        x_offset  = 0                  # crop left margin, start at cursor
        y_offset  = min_row - BASELINE  # negative = above baseline

        # Pack bits MSB-first, no row padding, pad last byte with zeros
        bits = []
        for row in range(min_row, max_row + 1):
            for col in range(min_col, max_col + 1):
                r, g, b = px[cx + col, row]
                bits.append(1 if max(r, g, b) >= THRESHOLD else 0)
            for _ in range(pad):
                bits.append(0)  # inter-LED gap column

        bitmap_offset = len(bitmap_bytes)
        for j in range(0, len(bits), 8):
            chunk = bits[j:j+8]
            byte = 0
            for bit in chunk:
                byte = (byte << 1) | bit
            byte <<= (8 - len(chunk))   # zero-pad last byte
            bitmap_bytes.append(byte)

        glyphs[code] = (bitmap_offset, gw, gh, x_advance, x_offset, y_offset)
        print(f"  0x{code:02X} '{c}': w={gw:2d} h={gh:2d} xa={x_advance:2d} yo={y_offset:+d}")

    # Space is not in CHARS (drawn implicitly), add it manually
    glyphs[0x20] = (0, 0, 0, SPACE_ADV, 0, 0)

    first_code = 0x20
    last_code  = max(glyphs.keys())

    # ── build header ──────────────────────────────────────────────────────────
    out = []
    out.append(f'// Generated by font_gen.py from font1.png')
    out.append(f'// Non-ASCII: 0x7F=£  0x80=€')
    out.append( '#pragma once')
    out.append( '')
    out.append( '#define FONT1_POUND 0x7F  // £')
    out.append( '#define FONT1_EURO  0x80  // €')
    out.append( '')

    out.append(f'const uint8_t {FONT_NAME}Bitmaps[] PROGMEM = {{')
    for i in range(0, len(bitmap_bytes), 16):
        chunk = bitmap_bytes[i:i+16]
        out.append('  ' + ', '.join(f'0x{b:02X}' for b in chunk) + ',')
    out.append('};')
    out.append('')

    out.append(f'const GFXglyph {FONT_NAME}Glyphs[] PROGMEM = {{')
    out.append( '  // bitmapOffset, width, height, xAdvance, xOffset, yOffset')
    for code in range(first_code, last_code + 1):
        if code in glyphs:
            bo, gw, gh, xa, xo, yo = glyphs[code]
            if code == 0x20:
                label = "' '"
            elif code == 0x7F:
                label = "'£'"
            elif code == 0x80:
                label = "'€'"
            elif 0x21 <= code < 0x7F:
                ch = chr(code)
                label = f'"{ch}"' if ch == "'" else f"'{ch}'"
            else:
                label = f'0x{code:02X}'
            out.append(f'  {{ {bo:5d}, {gw:3d}, {gh:3d}, {xa:3d}, {xo:3d}, {yo:4d} }},  // 0x{code:02X} {label}')
        else:
            out.append(f'  {{     0,   0,   0,   0,   0,    0 }},  // 0x{code:02X} (unused)')
    out.append('};')
    out.append('')

    out.append(f'const GFXfont {FONT_NAME} PROGMEM = {{')
    out.append(f'  (uint8_t  *){FONT_NAME}Bitmaps,')
    out.append(f'  (GFXglyph *){FONT_NAME}Glyphs,')
    out.append(f'  0x{first_code:02X},  // first (space)')
    out.append(f'  0x{last_code:02X},  // last (euro)')
    out.append(f'  {CELL_H}     // yAdvance')
    out.append('};')

    header = '\n'.join(out) + '\n'
    with open(OUT_PATH, 'w') as f:
        f.write(header)

    print(f'\nWrote {OUT_PATH}')
    print(f'  bitmap: {len(bitmap_bytes)} bytes')
    print(f'  glyphs: {last_code - first_code + 1} entries (0x{first_code:02X}–0x{last_code:02X})')


if __name__ == '__main__':
    main()
